using System.Collections.Generic;
using System.Text.Json.Serialization;
using Qos.Service.Activity;
using Qos.Service.Helper;
using Qos.Service.Models;
using Qos.Service.Models.Activity;
using Qos.Service.Models.Benchmarks;
using Qos.Service.Models.Cooling;
using Qos.Service.Models.Devices;
using Qos.Service.Models.Discord;
using Qos.Service.Models.Lifecycle;
using Qos.Service.Models.Lighting;
using Qos.Service.Models.Obs;
using Qos.Service.Models.Peripherals;
using Qos.Service.Models.Peripherals.Keeb;
using Qos.Service.Models.Peripherals.Q60;
using Qos.Service.Models.Peripherals.Y70;
using Qos.Service.Models.Sensors;
using Qos.Service.Models.Steam;
using Qos.Service.Platform;
using Qos.Service.Routes;

namespace Qos.Service.Serialization;

// Ping + Auth
[JsonSerializable(typeof(ApiResponse))]
[JsonSerializable(typeof(PingResponse))]
[JsonSerializable(typeof(PairResponse))]

// System / sensors
[JsonSerializable(typeof(PerformanceSnapshot))]
[JsonSerializable(typeof(HardwareSensor))]
[JsonSerializable(typeof(List<HardwareSensor>))]
[JsonSerializable(typeof(IReadOnlyList<HardwareSensor>))]
[JsonSerializable(typeof(HardwareComponent))]
[JsonSerializable(typeof(List<HardwareComponent>))]
[JsonSerializable(typeof(StorageComponent))]
[JsonSerializable(typeof(Dictionary<string, StorageComponent>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, StorageComponent>))]
[JsonSerializable(typeof(StorageDriveInfo))]
[JsonSerializable(typeof(SensorExtras))]
[JsonSerializable(typeof(GetModelResponse))]
[JsonSerializable(typeof(GetGpuModelsResponse))]
[JsonSerializable(typeof(CpuHealthResponse))]
[JsonSerializable(typeof(ProcessElevationResponse))]
[JsonSerializable(typeof(ProcessElevationRelaunchResponse))]
[JsonSerializable(typeof(GetStoragePartitionsResponse))]
[JsonSerializable(typeof(GetDriveStorageResponse))]
[JsonSerializable(typeof(SetPollingRateBody))]
[JsonSerializable(typeof(GetPollingRateResponse))]

// Cooling
[JsonSerializable(typeof(CoolingComponent))]
[JsonSerializable(typeof(GetAllCoolingResponse))]
[JsonSerializable(typeof(SetCurvesBody))]
[JsonSerializable(typeof(GetCurvesResponse))]

// Fan control
[JsonSerializable(typeof(FanChannel))]
[JsonSerializable(typeof(List<FanChannel>))]
[JsonSerializable(typeof(TemperatureSource))]
[JsonSerializable(typeof(List<TemperatureSource>))]
[JsonSerializable(typeof(GetFanChannelsResponse))]
[JsonSerializable(typeof(GetTemperatureSourcesResponse))]
[JsonSerializable(typeof(SetFanSpeedBody))]
[JsonSerializable(typeof(SetFanNameBody))]
[JsonSerializable(typeof(SetFanSpeedResponse))]
[JsonSerializable(typeof(CurveOutputState))]
[JsonSerializable(typeof(CurveCalculation))]
[JsonSerializable(typeof(CurveCalculationsFrame))]
[JsonSerializable(typeof(FanProfile))]
[JsonSerializable(typeof(List<FanProfile>))]
[JsonSerializable(typeof(GetProfilesResponse))]
[JsonSerializable(typeof(ApplyProfileResponse))]
[JsonSerializable(typeof(StartupModeBody))]
[JsonSerializable(typeof(StartupModeDto))]
[JsonSerializable(typeof(FanCalibration))]
[JsonSerializable(typeof(List<FanCalibration>))]
[JsonSerializable(typeof(FanCalibrationPoint))]
[JsonSerializable(typeof(List<FanCalibrationPoint>))]
[JsonSerializable(typeof(FanCalibrationProgress))]
[JsonSerializable(typeof(StartCalibrationBody))]
[JsonSerializable(typeof(CoolingStatusResponse))]
[JsonSerializable(typeof(LightingStatusResponse))]
[JsonSerializable(typeof(List<float>))]
[JsonSerializable(typeof(Qos.Service.Models.Lighting.MusicReactiveBody))]
[JsonSerializable(typeof(CalibrationStartResponse))]
[JsonSerializable(typeof(GetCalibrationsResponse))]

// Profiles
[JsonSerializable(typeof(Qos.Service.Persistence.ProfileManifest))]
[JsonSerializable(typeof(Qos.Service.Persistence.ProfileEntry))]
[JsonSerializable(typeof(List<Qos.Service.Persistence.ProfileEntry>))]
[JsonSerializable(typeof(Qos.Service.Persistence.UiSettings))]
[JsonSerializable(typeof(Qos.Service.Persistence.UiSettingsPatch))]

// Panel widget engine - per-device records, layouts, control-state push frames.
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelLayoutDto))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelPageDto))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelWidgetDto))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelConfigValue))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelDockDto))]
[JsonSerializable(typeof(List<Qos.Service.Models.Panel.PanelPageDto>))]
[JsonSerializable(typeof(List<Qos.Service.Models.Panel.PanelWidgetDto>))]
[JsonSerializable(typeof(Dictionary<string, Qos.Service.Models.Panel.PanelConfigValue>))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelDeviceRecord))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelDeviceCapabilities))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelDevicePatch))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelDeviceCreateBody))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelDeviceListResponse))]
[JsonSerializable(typeof(List<Qos.Service.Models.Panel.PanelDeviceRecord>))]
[JsonSerializable(typeof(Dictionary<string, Qos.Service.Models.Panel.PanelDeviceRecord>))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PrefsChangedFrame))]

// Desktop widgets - floating panel widgets on the Windows desktop.
[JsonSerializable(typeof(Qos.Service.Models.Panel.OverlayWidgetDto))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.OverlayWidgetCreateBody))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.OverlayWidgetPatch))]
[JsonSerializable(typeof(List<Qos.Service.Models.Panel.OverlayWidgetDto>))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.LightingChangedFrame))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.CoolingChangedFrame))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.DevicesChangedFrame))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelDeviceChangedFrame))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelPhonePairQrResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelPhoneClaimBody))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelPhoneClaimResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelPhoneServiceInfoResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelPhoneSessionNameBody))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelHostNameBody))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelHostNameResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelPhoneSessionsResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelPhoneSessionDto))]
[JsonSerializable(typeof(List<Qos.Service.Models.Panel.PanelPhoneSessionDto>))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.PanelStatusResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.RemoteControlStateResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.RemoteControlToggleRequest))]

// Displays (system monitors: brightness + DDC/CI VCP)
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayDto))]
[JsonSerializable(typeof(List<Qos.Service.Models.Displays.DisplayDto>))]
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayCapabilitiesDto))]
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayBrightnessControlDto))]
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayBrightnessWritePolicy))]
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayBrightnessDto))]
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayBrightnessParams))]
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayVcpDto))]
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayVcpParams))]
[JsonSerializable(typeof(Qos.Service.Models.Displays.DisplayListResponse))]

// Panel macros
[JsonSerializable(typeof(Qos.Service.Models.Panel.OpenUrlRequest))]
[JsonSerializable(typeof(Qos.Service.Models.Panel.ShortcutRequest))]

// Weather
[JsonSerializable(typeof(Qos.Service.Models.Weather.WeatherSnapshot))]
[JsonSerializable(typeof(Qos.Service.Models.Weather.WeatherHourlyForecast))]
[JsonSerializable(typeof(List<Qos.Service.Models.Weather.WeatherHourlyForecast>))]
[JsonSerializable(typeof(Qos.Service.Models.Weather.WeatherDailyForecast))]
[JsonSerializable(typeof(List<Qos.Service.Models.Weather.WeatherDailyForecast>))]
[JsonSerializable(typeof(Qos.Service.Platform.Weather.IpLocation))]
[JsonSerializable(typeof(Qos.Service.Platform.Weather.OpenMeteoResponse))]
[JsonSerializable(typeof(Qos.Service.Platform.Weather.OpenMeteoCurrent))]
[JsonSerializable(typeof(Qos.Service.Platform.Weather.OpenMeteoHourly))]
[JsonSerializable(typeof(Qos.Service.Platform.Weather.OpenMeteoDaily))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.ListProfilesResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.ProfileResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.SwitchProfileResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.CreateProfileBody))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.RenameProfileBody))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.ProfileExport))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.SharingResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.SetPrimaryBody))]
[JsonSerializable(typeof(Qos.Service.Models.Profiles.SetCategorySharedBody))]

// Media library
[JsonSerializable(typeof(Qos.Service.Models.Media.MediaItem))]
[JsonSerializable(typeof(List<Qos.Service.Models.Media.MediaItem>))]
[JsonSerializable(typeof(Qos.Service.Models.Media.MediaLibraryResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Media.MediaImportResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Media.MediaPlayResponse))]
[JsonSerializable(typeof(Qos.Service.Models.Media.MediaCurrentResponse))]

// Lighting
[JsonSerializable(typeof(AudioStateSnapshot))]
[JsonSerializable(typeof(ShaderSourceResponse))]
[JsonSerializable(typeof(CurrentSyncResponse))]
[JsonSerializable(typeof(SetFrameRateBody))]
[JsonSerializable(typeof(SetScaleRatioBody))]
[JsonSerializable(typeof(BrightnessScale))]
[JsonSerializable(typeof(SpeedScale))]
[JsonSerializable(typeof(StaticHeadlessStart))]
[JsonSerializable(typeof(AnimateHeadlessStart))]
[JsonSerializable(typeof(SetAnimateTemplatesBody))]
[JsonSerializable(typeof(ShaderParam))]
[JsonSerializable(typeof(List<ShaderParam>))]
[JsonSerializable(typeof(Qos.Service.Persistence.AnimateSettings))]
[JsonSerializable(typeof(Qos.Service.Persistence.AnimateEffectState))]
[JsonSerializable(typeof(Qos.Service.Persistence.AnimateEffectTemplates))]
[JsonSerializable(typeof(Qos.Service.Persistence.StaticColorSettings))]
[JsonSerializable(typeof(Dictionary<string, Qos.Service.Persistence.AnimateEffectState>))]
[JsonSerializable(typeof(Dictionary<string, Qos.Service.Persistence.AnimateEffectTemplates>))]
[JsonSerializable(typeof(List<Qos.Service.Persistence.AnimateEffectState>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, float>>))]
[JsonSerializable(typeof(MusicHeadlessStart))]
[JsonSerializable(typeof(ScreenHeadlessStart))]
[JsonSerializable(typeof(ScreenSyncOptions))]
[JsonSerializable(typeof(ScreenSyncMonitor))]
[JsonSerializable(typeof(List<ScreenSyncMonitor>))]
[JsonSerializable(typeof(GifHeadlessStart))]
[JsonSerializable(typeof(SetHeadlessStreaming))]
[JsonSerializable(typeof(Qos.Service.Models.Lighting.PostProcessBody))]
[JsonSerializable(typeof(Qos.Service.Persistence.PostProcessSettings))]

// OBS
[JsonSerializable(typeof(ObsConfigResponse))]
[JsonSerializable(typeof(ObsConfigBody))]
[JsonSerializable(typeof(ObsStatusResponse))]
[JsonSerializable(typeof(ObsScene))]
[JsonSerializable(typeof(List<ObsScene>))]
[JsonSerializable(typeof(ObsSetSceneBody))]

// Steam
[JsonSerializable(typeof(SteamConfigResponse))]
[JsonSerializable(typeof(SteamConfigBody))]
[JsonSerializable(typeof(SteamStatusResponse))]
[JsonSerializable(typeof(SteamProfileResponse))]
[JsonSerializable(typeof(SteamPlayerSummary))]
[JsonSerializable(typeof(SteamRecentGame))]
[JsonSerializable(typeof(List<SteamRecentGame>))]
[JsonSerializable(typeof(SteamOwnedGame))]
[JsonSerializable(typeof(List<SteamOwnedGame>))]
[JsonSerializable(typeof(SteamFriendSummary))]
[JsonSerializable(typeof(List<SteamFriendSummary>))]
[JsonSerializable(typeof(SteamAchievement))]
[JsonSerializable(typeof(List<SteamAchievement>))]

// Discord
[JsonSerializable(typeof(DiscordConfigResponse))]
[JsonSerializable(typeof(DiscordConfigBody))]
[JsonSerializable(typeof(DiscordStatusResponse))]
[JsonSerializable(typeof(DiscordUser))]
[JsonSerializable(typeof(DiscordGuild))]
[JsonSerializable(typeof(List<DiscordGuild>))]
[JsonSerializable(typeof(DiscordVoiceState))]
[JsonSerializable(typeof(DiscordVoiceParticipant))]
[JsonSerializable(typeof(List<DiscordVoiceParticipant>))]
[JsonSerializable(typeof(DiscordNotification))]
[JsonSerializable(typeof(List<DiscordNotification>))]
[JsonSerializable(typeof(DiscordOpenBody))]
[JsonSerializable(typeof(DiscordVoiceToggleBody))]

// Devices
[JsonSerializable(typeof(Qos.Service.Persistence.DeviceLayout))]
[JsonSerializable(typeof(SaveDeviceLayoutBody))]
[JsonSerializable(typeof(DeviceListItem))]
[JsonSerializable(typeof(List<DeviceListItem>))]
[JsonSerializable(typeof(UsbDeviceDetail))]
[JsonSerializable(typeof(List<UsbDeviceDetail>))]

// Peripherals (third-party mice/keyboards/headsets with protocol support)
[JsonSerializable(typeof(PeripheralDto))]
[JsonSerializable(typeof(List<PeripheralDto>))]
[JsonSerializable(typeof(GetPeripheralsResponse))]
[JsonSerializable(typeof(SupportedDeviceDto))]
[JsonSerializable(typeof(List<SupportedDeviceDto>))]
[JsonSerializable(typeof(GetSupportedDevicesResponse))]
[JsonSerializable(typeof(Qos.Service.Peripherals.OpenRgbSupportedDevicesFile))]
[JsonSerializable(typeof(Qos.Service.Peripherals.OpenRgbSupportedDeviceEntry))]
[JsonSerializable(typeof(List<Qos.Service.Peripherals.OpenRgbSupportedDeviceEntry>))]
[JsonSerializable(typeof(Qos.Service.Peripherals.Protocols.Razer.RazerMouseSpec))]
[JsonSerializable(typeof(Qos.Service.Peripherals.Protocols.Razer.RazerMouseSpecEntry))]
[JsonSerializable(typeof(List<Qos.Service.Peripherals.Protocols.Razer.RazerMouseSpecEntry>))]
[JsonSerializable(typeof(DpiState))]
[JsonSerializable(typeof(PollingState))]
[JsonSerializable(typeof(BatteryState))]
[JsonSerializable(typeof(SleepState))]
[JsonSerializable(typeof(ToggleState))]
[JsonSerializable(typeof(SetDpiBody))]
[JsonSerializable(typeof(SetPollingBody))]
[JsonSerializable(typeof(SetSleepBody))]
[JsonSerializable(typeof(SetToggleBody))]
[JsonSerializable(typeof(IsDeviceConnectedResponse))]
[JsonSerializable(typeof(FirmwareVersionResponse))]
[JsonSerializable(typeof(GetCnvsSettingsResponse))]
[JsonSerializable(typeof(SetCnvsSettingsBody))]
[JsonSerializable(typeof(UpdateBody))]
[JsonSerializable(typeof(CheckForUpdateResponse))]
[JsonSerializable(typeof(UpdateResponse))]
[JsonSerializable(typeof(GetMotherboardLEDsResponse))]
[JsonSerializable(typeof(SetMotherboardLEDsBody))]
[JsonSerializable(typeof(CheckFirmwareFunctionBody))]
[JsonSerializable(typeof(CheckFirmwareFunctionResponse))]
[JsonSerializable(typeof(GetLightingDevicesResponse))]
[JsonSerializable(typeof(SetDisabledLedsBody))]
[JsonSerializable(typeof(SetLightingDevicePowerBody))]
[JsonSerializable(typeof(SetLightingDeviceBrightness))]
[JsonSerializable(typeof(SetLightingDeviceHue))]
[JsonSerializable(typeof(SetLightingDeviceSaturation))]
[JsonSerializable(typeof(SetZoneLedCountBody))]
[JsonSerializable(typeof(IdentifyLightingDeviceBody))]
[JsonSerializable(typeof(LedMapResponse))]
[JsonSerializable(typeof(LedMapEntry))]
[JsonSerializable(typeof(List<LedMapEntry>))]
[JsonSerializable(typeof(SaveLedMapBody))]
[JsonSerializable(typeof(Qos.Service.Persistence.LedPositionOverride))]
[JsonSerializable(typeof(List<Qos.Service.Persistence.LedPositionOverride>))]
[JsonSerializable(typeof(LedHighlightBody))]
[JsonSerializable(typeof(LedTestPatternBody))]

// Keeb
[JsonSerializable(typeof(KeyboardState))]
[JsonSerializable(typeof(GetKeebSettingsResponse))]
[JsonSerializable(typeof(GetRotaryFunctionsResponse))]
[JsonSerializable(typeof(SetRotaryWheelsBody))]
[JsonSerializable(typeof(SetRotarySensitivityBody))]
[JsonSerializable(typeof(SetFirmwareLightingBody))]
[JsonSerializable(typeof(SetGameModeBody))]
[JsonSerializable(typeof(GetMacroResponse))]
[JsonSerializable(typeof(SetMacroBody))]
[JsonSerializable(typeof(InputterBody))]

// Displays
[JsonSerializable(typeof(Y70StatusResponse))]
[JsonSerializable(typeof(Y70RotationParams))]
[JsonSerializable(typeof(Y70BrightnessResponse))]
[JsonSerializable(typeof(Y70BrightnessParams))]
[JsonSerializable(typeof(Y70ToggleScreenResponse))]
[JsonSerializable(typeof(Y70ToggleScreenParams))]
[JsonSerializable(typeof(Y70IsRotatedResponse))]
[JsonSerializable(typeof(GetSerialNumberResponse))]
[JsonSerializable(typeof(GetQ60TimeResponse))]

// Activity
[JsonSerializable(typeof(FocusSession))]
[JsonSerializable(typeof(AppUsage))]
[JsonSerializable(typeof(List<AppUsage>))]
[JsonSerializable(typeof(IReadOnlyList<AppUsage>))]
[JsonSerializable(typeof(DayBreakdown))]
[JsonSerializable(typeof(DayTotal))]
[JsonSerializable(typeof(List<DayTotal>))]
[JsonSerializable(typeof(IReadOnlyList<DayTotal>))]
[JsonSerializable(typeof(AppHistory))]
[JsonSerializable(typeof(List<long>))]
[JsonSerializable(typeof(DeleteResponse))]
[JsonSerializable(typeof(TrackingStatus))]
[JsonSerializable(typeof(SetTrackingBody))]
[JsonSerializable(typeof(NetworkProcessInfo))]
[JsonSerializable(typeof(List<NetworkProcessInfo>))]
[JsonSerializable(typeof(IEnumerable<NetworkProcessInfo>))]
[JsonSerializable(typeof(List<Detected>))]
[JsonSerializable(typeof(KillAppResponse))]
[JsonSerializable(typeof(Dictionary<string, MediaSession>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, MediaSession>))]
[JsonSerializable(typeof(MediaControlBody))]
[JsonSerializable(typeof(VolumeState))]
[JsonSerializable(typeof(SetVolumeBody))]
[JsonSerializable(typeof(SetMutedBody))]
[JsonSerializable(typeof(GetAllShortcutsResponse))]
[JsonSerializable(typeof(GetShortcutResponse))]
[JsonSerializable(typeof(MusicResult))]

// Lifecycle
[JsonSerializable(typeof(SetWillStartParams))]
[JsonSerializable(typeof(WillStartResponse))]
[JsonSerializable(typeof(PawnIoStatus))]

// Processes
[JsonSerializable(typeof(ProcessInfo))]
[JsonSerializable(typeof(List<ProcessInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ProcessInfo>))]
[JsonSerializable(typeof(IEnumerable<ProcessInfo>))]

// Activity broadcaster (WebSocket push frames)
[JsonSerializable(typeof(ProcessFrame))]
[JsonSerializable(typeof(NetworkFrame))]
[JsonSerializable(typeof(ScreenTimeFrame))]

// Monitoring (multiplexed WebSocket composite frame)
[JsonSerializable(typeof(Qos.Service.Models.Monitoring.MonitoringFrame))]

// Benchmarks
[JsonSerializable(typeof(BenchmarkSubScore))]
[JsonSerializable(typeof(List<BenchmarkSubScore>))]
[JsonSerializable(typeof(BenchmarkPhaseProgress))]
[JsonSerializable(typeof(BenchmarkProgressFrame))]
[JsonSerializable(typeof(BenchmarkResult))]
[JsonSerializable(typeof(HardwareIdentity))]
[JsonSerializable(typeof(StartBenchmarkResponse))]
[JsonSerializable(typeof(StartBenchmarkBody))]

[JsonSerializable(typeof(float[]))]
[JsonSerializable(typeof(List<string>))]

// Helper IPC (Windows user-session companion process)
[JsonSerializable(typeof(HelperEnvelope))]
[JsonSerializable(typeof(HelperResult))]
[JsonSerializable(typeof(HelperHello))]
[JsonSerializable(typeof(TraySetVisiblePayload))]
[JsonSerializable(typeof(HelperShutdownPayload))]
[JsonSerializable(typeof(OverlayPrefsChangedPayload))]
[JsonSerializable(typeof(ServiceRequestStopPayload))]
[JsonSerializable(typeof(ScreenTimeSessionPayload))]
[JsonSerializable(typeof(ScreenTimeFocusPayload))]
[JsonSerializable(typeof(MediaSnapshotPayload))]
[JsonSerializable(typeof(MediaControlPayload))]
[JsonSerializable(typeof(AlbumArtRequest))]
[JsonSerializable(typeof(AlbumArtResult))]
[JsonSerializable(typeof(DisplayBrightnessRequest))]
[JsonSerializable(typeof(NullableIntResult))]
[JsonSerializable(typeof(DisplayVcpResult))]
[JsonSerializable(typeof(BoolResult))]
[JsonSerializable(typeof(StringResult))]
[JsonSerializable(typeof(DisplayListResult))]
[JsonSerializable(typeof(MonitorEnumerateRequest))]
[JsonSerializable(typeof(MonitorListResult))]
[JsonSerializable(typeof(ScreenMirrorStartPayload))]
[JsonSerializable(typeof(ScreenMirrorStopPayload))]
[JsonSerializable(typeof(ScreenMirrorFramePayload))]

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public partial class AppJsonContext : JsonSerializerContext;
