using System;
using System.Collections.Generic;
using System.Text.Json;
using Nexus.Service.Models.Devices;
using Nexus.Service.Serialization;

namespace Nexus.Service.Lighting.Mappings;

/// <summary>
/// The pre-built LED mappings that ship inside the binary: one artifact per
/// product a user can hang off an ARGB header (fans, strips, AIOs, blocks,
/// cases), keyed by a virtual <c>product:</c> key rather than by detected
/// hardware, because nothing on a header announces what is plugged into it.
///
/// Entirely local by design. An ARGB header is the one surface where the user
/// MUST tell us what they wired, so the picker has to work on a machine that
/// has never reached the network - no registry call, no cache warm-up, no
/// online account. Generated by nexus-dev/tools/argb-components and embedded
/// by the csproj; read once on first access and cached for the process.
/// </summary>
public static class BuiltInMappingsCatalog
{
    private const string ResourceName = "builtin-led-mappings.json";

    private static IReadOnlyList<BuiltInMappingEntry>? _entries;
    private static Dictionary<string, BuiltInMappingEntry>? _byKey;
    private static readonly object _gate = new();

    public static IReadOnlyList<BuiltInMappingEntry> All
    {
        get
        {
            EnsureLoaded();
            return _entries!;
        }
    }

    /// <summary>The artifact for a product key, or null when the key is not in the catalog.</summary>
    public static MappingArtifact? Find(string key)
    {
        EnsureLoaded();
        return _byKey!.TryGetValue(key, out var entry) ? entry.Artifact : null;
    }

    /// <summary>
    /// Substring search over product name, brand and type. Ranked so a name
    /// match beats a brand match and a prefix beats a mid-word hit, which is
    /// what makes typing "ql" surface the QL fan rather than every product
    /// whose description happens to contain those letters.
    /// </summary>
    public static List<BuiltInMappingSummary> Search(string? query, string? type, int limit)
    {
        EnsureLoaded();
        var q = query?.Trim();
        var hasQuery = !string.IsNullOrEmpty(q);
        var scored = new List<(int Rank, string Name, BuiltInMappingSummary Row)>();

        foreach (var entry in _entries!)
        {
            if (!string.IsNullOrEmpty(type)
                && !string.Equals(entry.Type, type, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var row = Summarize(entry);
            var rank = 0;
            if (hasQuery)
            {
                rank = RankMatch(row, q!);
                if (rank == int.MaxValue)
                    continue;
            }
            scored.Add((rank, row.Name, row));
        }

        scored.Sort((a, b) =>
        {
            var byRank = a.Rank.CompareTo(b.Rank);
            return byRank != 0 ? byRank : string.CompareOrdinal(a.Name, b.Name);
        });

        var take = limit > 0 ? Math.Min(limit, scored.Count) : scored.Count;
        var result = new List<BuiltInMappingSummary>(take);
        for (int i = 0; i < take; i++)
            result.Add(scored[i].Row);
        return result;
    }

    /// <summary>Lower is better; int.MaxValue means "no match".</summary>
    private static int RankMatch(BuiltInMappingSummary row, string query)
    {
        if (row.Name.StartsWith(query, StringComparison.OrdinalIgnoreCase)) return 0;
        if (row.Name.Contains(query, StringComparison.OrdinalIgnoreCase)) return 1;
        if (row.Brand.StartsWith(query, StringComparison.OrdinalIgnoreCase)) return 2;
        if (row.Brand.Contains(query, StringComparison.OrdinalIgnoreCase)) return 3;
        if (row.Type.Contains(query, StringComparison.OrdinalIgnoreCase)) return 4;
        return int.MaxValue;
    }

    private static BuiltInMappingSummary Summarize(BuiltInMappingEntry entry)
    {
        var artifact = entry.Artifact;
        var ledCount = 0;
        if (artifact.Zones.Count > 0 && artifact.Zones[0].LedCount is { } n)
            ledCount = n;
        return new BuiltInMappingSummary
        {
            Key = entry.Key,
            Name = artifact.Name,
            Brand = artifact.Device.Match?.VendorHint ?? "",
            Type = entry.Type,
            LedCount = ledCount,
        };
    }

    private static void EnsureLoaded()
    {
        if (_entries is not null)
            return;
        lock (_gate)
        {
            if (_entries is not null)
                return;
            var entries = Load();
            var byKey = new Dictionary<string, BuiltInMappingEntry>(entries.Count, StringComparer.Ordinal);
            foreach (var entry in entries)
                byKey[entry.Key] = entry;
            _byKey = byKey;
            _entries = entries;
        }
    }

    private static List<BuiltInMappingEntry> Load()
    {
        var asm = typeof(BuiltInMappingsCatalog).Assembly;
        using var stream = asm.GetManifestResourceStream(ResourceName);
        if (stream is null)
        {
            Console.Error.WriteLine($"[mappings] built-in catalog resource {ResourceName} missing");
            return new List<BuiltInMappingEntry>();
        }
        try
        {
            var file = JsonSerializer.Deserialize(stream, AppJsonContext.Default.BuiltInMappingsFile);
            return file?.Mappings ?? new List<BuiltInMappingEntry>();
        }
        catch (Exception ex)
        {
            // An unreadable catalog costs the assign picker, nothing else, so
            // degrade to empty rather than taking the lighting page down.
            Console.Error.WriteLine($"[mappings] built-in catalog unreadable: {ex.Message}");
            return new List<BuiltInMappingEntry>();
        }
    }
}
